name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user_user
          POSTGRES_PASSWORD: user_pass
          POSTGRES_DB: user_db_test
        options: >-
          --health-cmd="pg_isready -U user_user" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r ./UserService/requirements.txt  # Adjust for each service

      - name: Run UserService Tests
        run: |
          python -m unittest discover -s ./UserService